-- Create Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  original_price numeric,
  category_id bigint references categories(id),
  brand text,
  condition text check (condition in ('New', 'Used')),
  stock integer default 0,
  image_url text,
  images jsonb default '[]'::jsonb, -- Array of additional image URLs
  specs jsonb default '{}'::jsonb, -- JSON object for specs (chip, camera, battery)
  is_featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Product Variants Table (for Color/Storage)
create table product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  name text, -- Optional now, can be generated from color/storage
  color text,
  storage text,
  price numeric, -- Overrides base price if set
  price_adjustment numeric default 0, -- Kept for backward compatibility or additional logic
  stock integer default 0,
  sku text
);

-- Create Profiles Table (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone text,
  address text,
  role text default 'admin' check (role in ('customer', 'admin', 'staff')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  total_price numeric not null,
  status text default 'pending' check (status in ('pending', 'paid', 'processing', 'shipped', 'completed', 'cancelled')),
  payment_method text,
  slip_url text,
  shipping_address text,
  tracking_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items Table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id),
  variant_id bigint references product_variants(id),
  quantity integer not null,
  price numeric not null -- Price at the time of purchase
);

-- Insert some initial categories
insert into categories (name, slug) values
('Mobile Phones', 'mobile-phones'),
('Tablets', 'tablets'),
('Accessories', 'accessories'),
('Gadgets', 'gadgets');

-- Create a trigger to automatically create a profile for new users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'customer');
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table products enable row level security;
alter table orders enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Policies for Products
create policy "Products are viewable by everyone"
  on products for select
  using ( true );

create policy "Admins can insert products"
  on products for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Admins can update products"
  on products for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Admins can delete products"
  on products for delete
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Policies for Orders
create policy "Users can view their own orders"
  on orders for select
  using ( auth.uid() = user_id );

create policy "Admins can view all orders"
  on orders for select
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Users can insert their own orders"
  on orders for insert
  with check ( auth.uid() = user_id );

create policy "Admins can update orders"
  on orders for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Storage Setup (Run this manually if migration fails)
-- insert into storage.buckets (id, name, public) values ('products', 'products', true);

-- Storage Policies
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'products' );
-- create policy "Admin Upload" on storage.objects for insert with check ( bucket_id = 'products' and exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );
-- create policy "Admin Delete" on storage.objects for delete using ( bucket_id = 'products' and exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Phase 6: Advanced Order Statuses
-- Run this to update the check constraint
-- alter table orders drop constraint orders_status_check;
-- alter table orders add constraint orders_status_check 
--   check (status in ('pending', 'paid', 'preparing', 'shipped', 'completed', 'cancelled', 'returned', 'refunded'));

-- Phase 6: Inventory Management
-- Create Branches Table
create table branches (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Product Stock Table
create table product_stock (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  branch_id bigint references branches(id) on delete cascade,
  quantity integer default 0 check (quantity >= 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(product_id, branch_id)
);

-- Enable RLS
alter table branches enable row level security;
alter table product_stock enable row level security;

-- Policies
create policy "Public can view branches" on branches for select using (true);
create policy "Admins can manage branches" on branches for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Public can view stock" on product_stock for select using (true);
create policy "Admins can manage stock" on product_stock for all using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Insert Default Branches
insert into branches (name, location) values 
('Main Warehouse', 'Bangkok HQ'),
('Siam Paragon Store', 'Bangkok'),
('Central World Store', 'Bangkok');
