-- Create carriers table
CREATE TABLE IF NOT EXISTS carriers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default carriers
INSERT INTO carriers (name) VALUES 
  ('Kerry'), 
  ('J&T'), 
  ('SPX'), 
  ('Flash')
ON CONFLICT (name) DO NOTHING;
